# Generated by Django 5.0.7 on 2024-08-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_product_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="medical_indications",
            field=models.TextField(
                blank=True,
                help_text="Укажите медицинские показания",
                null=True,
                verbose_name="Медицинские показания",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="restrictions",
            field=models.TextField(
                blank=True,
                help_text="Укажите любые ограничения на продукт",
                null=True,
                verbose_name="Ограничения",
            ),
        ),
    ]
