# Generated by Django 5.0.7 on 2024-08-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание темы",
                null=True,
                verbose_name="Описание темы",
            ),
        ),
    ]
