# Generated by Django 5.0.7 on 2024-08-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_home_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="home",
            options={"verbose_name": "Тема", "verbose_name_plural": "Темы"},
        ),
    ]
