# Generated by Django 5.0.7 on 2024-08-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите ваше имя", max_length=150, verbose_name="Имя"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="Введите вашу фамилию",
                        max_length=150,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        help_text="Введите ваше отчество",
                        max_length=150,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите ваш email",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Введите ваш номер телефона",
                        max_length=35,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите, куда вы хотите записаться",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.product",
                        verbose_name="Запись на прием",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аккаунт",
                "verbose_name_plural": "Аккаунты",
            },
        ),
    ]
